### ISSUE TITLE
Minimum versions of packages in environment

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/2023-workshop-vignettes#1]
I'm opening this issue to track the constraints my vignettes will introduce into an environment designed to be able to run all of them. Feel free to add to or edit this list

Constraints derived from features I need:
* `openff-toolkit >=0.13` for multi-component PDB loading
* `openff-forcefields >=2023.05` for easier access to a 4-site water model
* `openff-interchange >=0.3.2` for _gestures broadly_
* `openff-nagl >= 0.2.2`
* `openff-nagl-models >=0.0.2`
* `openff-toolkit-examples` for nglview, notebook, qc stack

Packages I don't think my vignettes use, but others might:
* `openff-evaluator`

Other constraints that are probably implicit in packaging:
* `python >=3.9`
* `openff-units >=0.2.0`
* `pint >=0.21`
* `openmm >=7.6`

**Comment by j-wags** [comment]
added nagl and nagl-models
