### ISSUE TITLE
Broken Colab link: Protein-ligand complex via Interchange combination

### ISSUE THREAD

**Issue by rohithmohan** [openforcefield/2023-workshop-vignettes#7]
Hi, I noticed that the link to the "Protein-ligand complex via Interchange combination" vignette Colab is broken. From the commits it looks like the name of the notebook was changed from G-protein-ligand.ipynb to Y-interchange-combination-export.ipynb

Thanks for collecting and providing these notebooks!

**Comment by mattwthompson** [comment]
Thanks for catching this! It should be fixed in the README now.
